name: continuous integration

# Build every push and every pull request
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        jdk: [ 8, 11, 12, 13, 14 ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache maven deps
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: maven-${{ matrix.jdk }}-${{ hashFiles('**/pom.xml') }}

    - name: Select JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.jdk }}
        distribution: adopt

    # Run all the way to the install goal to have artifacts
    # in the local maven repo. we need them for later dependency
    # analysis
    - name: Build
      run: mvn --batch-mode --no-transfer-progress install --file pom.xml

    - name: Dependecy Analysis
      run: mvn dependency:tree --file pom.xml -Dverbose
